### PR TITLE
libnvhost1x: initialize struct to please valgrind

### PR DESCRIPTION
**Pull request by kusma**
This removes a valgrind warning

### CODE REVIEW

**Comment by digetx** [comment]
Valgrind complains about all IOCTL's that it's not aware of. Probably it is not the only one it complains about, isn't it?

**Comment by kusma** [comment]
@digetx: Somehow doesn't seems like it. I'm not really sure, but this made this go away. I don't really care though, so if you don't like this, let's drop it.

**Comment by digetx** [comment]
@kusma I have checked it on my side, indeed this is the first IOCTL which valgrind complains about. After applying your patch, valgrind complains about TEGRA_DC_EXT_SET_NVMAP_FD and so on. So yeah, not much sense in suppressing only one IOCTL of many.

**Comment by digetx** [comment]
I'm pretty sure you should get the same result as me.

**Comment by kusma** [comment]
I might have scanned the output too quickly. In either case, let's drop this.

**Pull request closed without merging**
