### PR TITLE
More grate tests

### PR DESCRIPTION
**Pull request by digetx**
I think we need some interactive =)

### CODE REVIEW

**Comment by digetx** [comment]
BTW, seems perspective projection matrix is not correct. Cube gets skewed when drawn at the side of a screen (widescreen aspect). Just a note, I may check the mat a bit later.

**Comment by kusma** [comment]
making a game? ;)

**Comment by kusma** [comment]
Looks good :)

**Comment by digetx** [comment]
Shouldn't take much effort to turn it into some trivial game eventually, but.... meeeh. Not a gamer :P

**Pull request merged**
