### PR TITLE
Pixbuf BO guard

### PR DESCRIPTION
**Pull request by digetx**
That gives some confidence.

### CODE REVIEW

**Comment by kusma** [comment]
The naming here seems a bit confused to me... ["guard band"](http://developer.download.nvidia.com/assets/gamedev/docs/Guard_Band_Clipping.pdf) is already used as a term in 3D renderering, but not for something like this...

**Comment by digetx** [comment]
Okay, I'll drop the "band".

**Comment by digetx** [comment]
Dropped ;)

**Comment by digetx** [comment]
So?

**Comment by kusma** [comment]
Sorry, I kind of forgot about this one. I'm not crazy about it as-is... it seems like useful debugging functionality, but I'm not so sure about it being on always. Wouldn't it be OK to make it opt-in instead?

**Comment by digetx** [comment]
Should be OK, I'll add grate cmdline option.

**Comment by digetx** [comment]
Added the cmdline option.

**Review by kusma — APPROVED** [review]
Looks good!

**Pull request merged**
