### PR TITLE
Vertex assembler

### PR DESCRIPTION
**Pull request by digetx**
There is no asm syntax description yet, some variants: to add a readme, create a wiki page (preferred), it's not needed at all or something else. If this patchset looks okay, please let me know what to choose.

### CODE REVIEW

**Review by kusma — APPROVED** [review]
Looks great, thanks :)

**Comment by digetx** [comment]
Great! 👍
I think it's time for the fragment shader, should be even more fun!

**Comment by kusma** [comment]
Yeah, the fragment shader really need some low-level peeking to figure out the timing etc :)

**Comment by digetx** [comment]
I don't think that it uses delay slots or whatever timing constraints, should be couple staggered ALU's as described in the patents. I hope we could getaway with some bare minimum :) The good thing that there are much more public nvidia patents on the fragment shader pipeline than on vertex and they seems to be a bit useful, at least giving some insight.

BTW,  you haven't answered regarding the asm syntax description. I think a wiki page should be good enough, I'll add it once will get too tired of the fragment stuff :) Anyway, syntax should be quite obvious by looking at the asm test samples, it was partially inspired by the freedreno's asm.

**Comment by kusma** [comment]
@digetx: A wiki page for the ASM syntax description would be nice, yeah :)

**Pull request merged**
