### PR TITLE
Libwrap

### PR DESCRIPTION
**Pull request by digetx**
dlsym now works properly

### CODE REVIEW

**Comment by digetx** [comment]
@kusma Libwrap now partially works with glxgears. At least glxgears is not exiting immediately with error, but tracing isn't working because FD of `/dev/dri/card0` mismatches the FD that is used for DRM IOCTL's. I can't figure out why... could you take a look? I don't see any dup(FD) calls or anything like that, the FD number is off by 1 or 2 for `open()` vs `ioctl()` and it's the traced FD that  is invalid.

**Comment by digetx** [comment]
Actually there is `fcntl(screen->fd, F_DUPFD_CLOEXEC, 3)`

**Comment by digetx** [comment]
It works now.

**Comment by digetx** [comment]
@kusma Should be good.

**Comment by kusma** [comment]
Nice!

**Pull request merged**
