### PR TITLE
cleanup command stream

### PR DESCRIPTION
**Pull request by kusma**
These are just a few small changes to simplify the command-stream.

### CODE REVIEW

**Comment by digetx** [comment]
Unfortunately stencil test breaks without the magic init. Comment out `grate_wait_for_key` from the stenci.c and run `while :; do ./stencil -f || break; done`. Seems you removed too much :)

**Comment by kusma** [comment]
@digetx: Aha, interesting. I'll rework this later, then :)

**Comment by kusma** [comment]
@digetx: OK, dropped the code-removal in favor of just moving and naming things a bit more.

**Review by digetx — APPROVED** [review]
No regressions this time, neat! 👍

**Pull request merged**
